### PR TITLE
Release v0.3.1, make package noarch, and rerendered.

### PR DESCRIPTION
**Pull request by pelson**
@bjlittle - I confess, I don't know the impact of this becoming noarch on downstream scripts... perhaps we need to just suck it and see... 🙀

### CODE REVIEW

**Comment by bjlittle** [comment]
@pelson Don't quite understand why the build failed ...

**Comment by pelson** [comment]
Me neither... https://github.com/conda/conda-build/issues/2362#issuecomment-344603157 😉 

I have pushed a fix. Let's see how that does.

**Comment by bjlittle** [comment]
@pelson So we don't trample on each other toes, I'll push the `conda-build-all` changes to it's feedstock ...

**Comment by pelson** [comment]
Thanks @bjlittle. I've cut the tag.

**Comment by pelson** [comment]
All good this end.

**Comment by pelson** [comment]
🤞  for downstream ... 😉

**Comment by bjlittle** [comment]
Just about to find that out ... \<gulp\>

**Comment by bjlittle** [comment]
@pelson Downstream is good! 🍻

**Pull request merged**
