### PR TITLE
Update to v0.3.0

### PR DESCRIPTION
**Pull request by bjlittle**
Bump to the latest version.

### CODE REVIEW

**Comment by bjlittle** [comment]
@pelson Something weird is happening with the appveyor build ... any ideas?

**Comment by pelson** [comment]
@conda-forge-admin, please rerender

**Comment by pelson** [comment]
Strange windows issue... 

```
The following packages will be SUPERSEDED by a higher-priority channel:
    conda:            4.3.30-py27h55876ee_0 defaults    --> 4.3.29-py27_0 conda-forge
    conda-env:        2.6.0-h36134e3_1      defaults    --> 2.6.0-0       conda-forge
    openssl:          1.0.2l-vc9h9275bb0_2  defaults    --> 1.0.2l-vc9_0  conda-forge [vc9]
    yaml:             0.1.7-vc9hdc2d5c9_1   defaults    --> 0.1.6-vc9_0   conda-forge [vc9]
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::jupyter_core-4.4.0-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
```

**Comment by pelson** [comment]
I've asked conda-forge to rerender this feedstock (and update your PR). Incoming...

**Comment by bjlittle** [comment]
@pelson LGTM 👍

**Comment by bjlittle** [comment]
Awesome, thanks @pelson !

**Pull request merged**
